const state = { token: localStorage.getItem("prompt-lens-admin-token") || "", view: "users", users: [], jobs: [] };
const $ = (id) => document.getElementById(id);
const labels = { processing: ["处理中", "warn"], succeeded: ["已完成", "ok"], failed: ["已失败", "bad"] };
function toast(message) { const node = $("toast"); node.textContent = message; node.classList.add("show"); clearTimeout(toast.timer); toast.timer = setTimeout(() => node.classList.remove("show"), 2600); }
async function request(path, options = {}) { const response = await fetch(path, { ...options, headers: { "Content-Type": "application/json", "X-Admin-Token": state.token, ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(data.detail || "请求失败"); error.status = response.status; throw error; } return data; }
function renderMetrics(data) { const items = [["users", "用户总数", data.users, data.active_users + " 个正常"], ["jobs", "分析任务", data.jobs, "处理中 " + data.processing], ["succeeded", "完成任务", data.succeeded, "失败 " + data.failed], ["credits", "用户持有积分", data.credits, "累计消耗 " + data.consumed_credits], ["ad_claims", "广告奖励次数", data.ad_claims, "每日上限 " + data.ad_daily_limit]]; $("metrics").innerHTML = items.map((item) => "<div class=\"metric\"><label>" + item[1] + "</label><strong>" + item[2] + "</strong><small>" + item[3] + "</small></div>").join(""); }
function statusTag(status) { const value = labels[status] || [status, "warn"]; return "<span class=\"status " + value[1] + "\">" + value[0] + "</span>"; }
function renderTable() { const table = $("dataTable"); table.hidden = false; $("tableState").hidden = true; if (state.view === "users") { $("tableHead").innerHTML = "<tr><th>ID</th><th>OpenID</th><th>积分</th><th>状态</th><th>注册时间</th><th></th></tr>"; $("tableBody").innerHTML = state.users.map((user) => "<tr><td>#" + user.id + "</td><td><code>" + user.openid + "</code></td><td><strong>" + user.credits + "</strong></td><td>" + (user.is_blocked ? "<span class=\"status bad\">已封禁</span>" : "<span class=\"status ok\">正常</span>") + "</td><td>" + new Date(user.created_at).toLocaleString() + "</td><td><button class=\"action\" data-user=\"" + user.id + "\">查看</button></td></tr>").join("") || "<tr><td colspan=\"6\">暂无用户</td></tr>"; } else { $("tableHead").innerHTML = "<tr><th>ID</th><th>用户</th><th>媒体</th><th>状态</th><th>积分</th><th>时间</th><th></th></tr>"; $("tableBody").innerHTML = state.jobs.map((job) => "<tr><td>#" + job.id + "</td><td><code>" + job.openid + "</code></td><td>" + (job.mode === "video" ? "视频" : "图片") + "</td><td>" + statusTag(job.status) + "</td><td>" + job.cost + "</td><td>" + new Date(job.created_at).toLocaleString() + "</td><td>" + (job.status === "succeeded" ? "<button class=\"action\" data-refund=\"" + job.id + "\">退款</button>" : "") + "</td></tr>").join("") || "<tr><td colspan=\"7\">暂无任务</td></tr>"; } }
async function load() { try { renderMetrics(await request("/api/admin/overview")); if (state.view === "users") state.users = await request("/api/admin/users?query=" + encodeURIComponent($("searchInput").value)); else state.jobs = await request("/api/admin/jobs?status=" + encodeURIComponent($("statusSelect").value)); renderTable(); } catch (error) { if (error.status === 401) return showLogin(); toast(error.message); } }
function showLogin() { $("loginView").hidden = false; $("appView").hidden = true; localStorage.removeItem("prompt-lens-admin-token"); state.token = ""; }
function showApp() { $("loginView").hidden = true; $("appView").hidden = false; load(); }
async function login(event) { event.preventDefault(); $("loginError").textContent = ""; try { const data = await request("/api/admin/login", { method: "POST", body: JSON.stringify({ username: $("username").value, password: $("password").value }), headers: { "X-Admin-Token": "" } }); state.token = data.token; localStorage.setItem("prompt-lens-admin-token", state.token); showApp(); } catch (error) { $("loginError").textContent = error.message; } }
async function openUser(id) { const data = await request("/api/admin/users/" + id); const user = data.user; $("drawerTitle").textContent = "用户 #" + user.id; $("drawerBody").innerHTML = "<div class=\"detail-card\"><div class=\"detail-row\"><span>OpenID</span><strong>" + user.openid + "</strong></div><div class=\"detail-row\"><span>当前积分</span><strong>" + user.credits + "</strong></div><div class=\"detail-row\"><span>状态</span><strong>" + (user.is_blocked ? "已封禁" : "正常") + "</strong></div><div class=\"detail-row\"><span>注册时间</span><strong>" + new Date(user.created_at).toLocaleString() + "</strong></div></div><div class=\"drawer-actions\"><button class=\"action\" data-adjust=\"" + user.id + "\">调整积分</button><button class=\"action\" data-block=\"" + user.id + "\" data-blocked=\"" + user.is_blocked + "\">" + (user.is_blocked ? "解除封禁" : "封禁用户") + "</button></div><div class=\"detail-card\"><p class=\"kicker\">最近流水</p>" + data.ledger.slice(0, 10).map((item) => "<div class=\"detail-row\"><span>" + item.reason + "</span><strong>" + (item.amount > 0 ? "+" : "") + item.amount + "</strong></div>").join("") + "</div>"; $("drawer").hidden = false; }
function openCredit(id) { $("creditUserId").value = id; $("creditAmount").value = ""; $("creditReason").value = ""; $("creditError").textContent = ""; $("modal").hidden = false; }
async function adjustCredit(event) { event.preventDefault(); try { await request("/api/admin/users/" + $("creditUserId").value + "/credits", { method: "POST", body: JSON.stringify({ amount: Number($("creditAmount").value), reason: $("creditReason").value }) }); $("modal").hidden = true; toast("积分已调整"); await load(); } catch (error) { $("creditError").textContent = error.message; } }
document.addEventListener("DOMContentLoaded", () => { $("loginForm").addEventListener("submit", login); $("logoutButton").addEventListener("click", async () => { try { await request("/api/admin/logout", { method: "POST" }); } finally { showLogin(); } }); $("refreshButton").addEventListener("click", load); $("searchButton").addEventListener("click", load); $("closeDrawer").addEventListener("click", () => { $("drawer").hidden = true; }); $("closeModal").addEventListener("click", () => { $("modal").hidden = true; }); $("creditForm").addEventListener("submit", adjustCredit); document.querySelectorAll(".tab").forEach((button) => button.addEventListener("click", () => { state.view = button.dataset.view; document.querySelectorAll(".tab").forEach((item) => item.classList.toggle("active", item === button)); load(); })); document.addEventListener("click", async (event) => { const user = event.target.closest("[data-user]"); if (user) openUser(user.dataset.user); const adjust = event.target.closest("[data-adjust]"); if (adjust) openCredit(adjust.dataset.adjust); const block = event.target.closest("[data-block]"); if (block) { const endpoint = block.dataset.blocked === "1" ? "unblock" : "block"; await request("/api/admin/users/" + block.dataset.block + "/" + endpoint, { method: "POST" }); toast("用户状态已更新"); await openUser(block.dataset.block); await load(); } const refund = event.target.closest("[data-refund]"); if (refund) { if (!window.confirm("确认给该任务退款？")) return; await request("/api/admin/jobs/" + refund.dataset.refund + "/refund", { method: "POST" }); toast("已退款"); await load(); } }); if (state.token) showApp(); });
